CREATE CONSTRAINT FOR (u:Client)
REQUIRE u.id IS UNIQUE

CREATE CONSTRAINT FOR (p:Preference)
REQUIRE p.name IS UNIQUE

CREATE CONSTRAINT FOR (b:Bloq)
REQUIRE b.id IS UNIQUE

CREATE CONSTRAINT FOR (b:Bloq)
REQUIRE b.name IS NOT NULL

CREATE CONSTRAINT FOR (b:Bloq)
REQUIRE b.description IS NOT NULL

CREATE CONSTRAINT FOR (b:Bloq)
REQUIRE b.price IS NOT NULL

CREATE CONSTRAINT FOR ()-[b:Bought]-()
REQUIRE b.rate IS NOT NULL
